ingress:
  enabled: false
  default:
    isolateByLabel: false
    labelKey: ingress-type
    reservedValues:
      - public
      - private
  private:
    enabled: false
    name: private
    domain: ""
    replicas: 2
    scope: Internal
    routeSelector:
      key: ingress-type
      value: private
    namespaceSelector: {}
    nodePlacement: {}
    certificate:
      enabled: false
      issuer: letsencrypt-prod
      secretName: private-ingress-tls
  public:
    enabled: false
    name: public
    domain: ""
    replicas: 2
    scope: External
    routeSelector:
      key: ingress-type
      value: public
    namespaceSelector: {}
    nodePlacement: {}
    certificate:
      enabled: false
      issuer: letsencrypt-prod
      secretName: public-ingress-tls
