# Informações básicas do Cluster ROSA
clusterName: "rosa-5zbzk"
cloudType: "AWS"        # Define o provider como AWS no ACM
baseDomain: "p3.openshiftapps.com"

# Labels de Governança e Automação
labels:
  env: "staging"
  region: "us-east-2"
  vendor: "OpenShift"
  cloud: "AWS"
  # Label que faz o ArgoCD importar este cluster como um 'Destination'
  apps.open-cluster-management.io/replicate-to-argocd: "true"
  # Label para aplicar políticas de segurança específicas
  security-tier: "standard"
  # Label para o Placement Rule de monitorização
  monitoring: "enabled"

# Configurações de Add-ons do ACM (Klusterlet)
addons:
  policyController: true
  searchCollector: true
  applicationManager: true
  certPolicyController: true

# Credenciais para Auto-Import (Opcional)
# O ACM usará estas chaves para injetar o agente no ROSA remotamente
cloudCredentials:
  aws_access_key_id: "PLACEHOLDER"
  aws_secret_access_key: "PLACEHOLDER"
  region: "us-east-2"
