# O nome exato do cluster (usado para criar o Namespace no Hub, o ManagedCluster e buscar no Vault)
clusterName: rosaqa

# Provedor de nuvem (usado como label no ManagedCluster para facilitar filtros no ACM)
cloudProvider: ROSA

# Ambiente (usado como label no ManagedCluster)
environment: qa
clusterSet: global-clusters
vendor: OpenShift
labels:
  env: "qa"
  region: "eastus"
  vendor: "OpenShift"
  cloud: "AWS"
  criticality: "high"
  apps.open-cluster-management.io/replicate-to-argocd: "true"
  compliance: "pci-dss"
  reimport: "true"
addons:
  policyController: true
  searchCollector: true
  applicationManager: true
