clusterName: "aro-cluster-clhxs"
cloudType: "Azure"
baseDomain: "eastus.aroapp.io"
labels:
  env: "production"
  region: "eastus"
  vendor: "OpenShift"
  cloud: "Azure"
  criticality: "high"
  apps.open-cluster-management.io/replicate-to-argocd: "true"
  compliance: "pci-dss"
addons:
  policyController: true
  searchCollector: true
  applicationManager: true
cloudCredentials:
  subscriptionId: "REPLACE_IN_CLUSTER"
  tenantId: "REPLACE_IN_CLUSTER"
  clientId: "REPLACE_IN_CLUSTER"
  clientSecret: "REPLACE_IN_CLUSTER"
