clusterName: "aro-cluster-teste"
cloudType: "Azure"
baseDomain: "eastus.aroapp.io"
cloudProvider: "Azure"
environment: "test"
clusterSet: "global-clusters"
apps.open-cluster-management.io/replicate-to-argocd: "true"
labels:
  env: "prod"
  region: "eastus"
  vendor: "OpenShift"
  cloud: "Azure"
  criticality: "high"
  apps.open-cluster-management.io/replicate-to-argocd: "true"
  compliance: "pci-dss"
addons:
  policyController: true
  searchCollector: true
  applicationManager: true

