apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: get-spoke-kubeconfig
  namespace: {{ .Values.clusterName }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aro-cluster-secretstore # SecretStore do seu Hub
    kind: ClusterSecretStore
  target:
    name: auto-import-secret # O ACM EXIGE este nome!
    template:
      type: Opaque
      data:
        # A flag autoImportRetry diz pro ACM tentar conectar repetidamente 
        # (útil se o cluster ainda estiver subindo na nuvem)
        autoImportRetry: "5"
        # O Kubeconfig decodificado do Vault
        #kubeconfig: "{{ .kubeconfig_raw | b64dec }}"
        kubeconfig: '{{`{{ .kubeconfig_raw }}`}}'
  data:
    - secretKey: kubeconfig_raw
      remoteRef:
        key: {{ .Values.clusterName }}-kubeconfig
        decodingStrategy: Base64


