apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: {{ .Values.clusterName }}
  labels:
    cluster.open-cluster-management.io/backup: cluster-activation
type: Opaque
stringData:
  autoImportRetry: "5"
  # O token e o server devem ser injetados de forma segura
  server: {{ .Values.cluster.apiServerUrl }}
  token: {{ .Values.cluster.adminToken }}
