apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-auth-es
  namespace: {{ .Values.clusterName }} # Namespace do cluster no Hub
spec:
  # Refere-se ao SecretStore que você já configurou na integração com a Azure
  secretStoreRef:
    name: gcp-cluster-secretstore
    kind: ClusterSecretStore # Ou ClusterSecretStore, dependendo da sua instalação
  
  target:
    # Este é o nome do Secret REAL que o ACM vai procurar
    name: auto-import-secret
    template:
      type: Opaque
      metadata:
        labels:
          # Labels cruciais para o ACM reconhecer o segredo
          cluster.open-cluster-management.io/type: azure
          cluster.open-cluster-management.io/credentials: ""
      # Formatação dos dados para o padrão que o ACM exige
  data:
    # Mapeamento: 'secretKey' é o nome dentro da Vault, 'remoteRef' é a chave na Azure
    - secretKey: kubeconfig
      remoteRef:
        key: AROKUBETDCWT
