apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-auth-es
  namespace: {{ .Values.clusterName }} # Namespace do cluster no Hub
spec:
  # Refere-se ao SecretStore que você já configurou na integração com a Azure
  secretStoreRef:
    name: azure-secretstore
    kind: SecretStore # Ou ClusterSecretStore, dependendo da sua instalação
  
  target:
    # Este é o nome do Secret REAL que o ACM vai procurar
    name: {{ .Values.clusterName }}-auth 
    template:
      metadata:
        labels:
          # Labels cruciais para o ACM reconhecer o segredo
          cluster.open-cluster-management.io/type: azure
          cluster.open-cluster-management.io/credentials: ""
      # Formatação dos dados para o padrão que o ACM exige
      data:
        osServicePrincipal.clientId: "{ { .client_id | toString } }"
        osServicePrincipal.clientSecret: "{ { .client_secret | toString } }"
        osServicePrincipal.tenantId: "{ { .tenant_id | toString } }"
        osServicePrincipal.subscriptionId: "{ { .subscription_id | toString } }"

  data:
    # Mapeamento: 'secretKey' é o nome dentro da Vault, 'remoteRef' é a chave na Azure
    - secretKey: clientId
      remoteRef:
        key: {{ .Values.externalSecrets.vaultKeys.clientId }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.externalSecrets.vaultKeys.clientSecret }}
    - secretKey: tenant_id
      remoteRef:
        key: {{ .Values.externalSecrets.vaultKeys.tenantId }}
    - secretKey: subscription_id
      remoteRef:
        key: {{ .Values.externalSecrets.vaultKeys.subscriptionId }}
