apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    # Vincula ao Set que o ArgoCD tem permissão de ver
    cluster.open-cluster-management.io/clusterset: global-clusters
    # Faz o ACM criar o Secret de conexão no namespace do ArgoCD automaticamente
    apps.open-cluster-management.io/replicate-to-argocd: "true"
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  hubAcceptsClient: true
