# charts/import-cluster/templates/push-secret.yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-import-manifest-{{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }} # <--- Valor dinâmico baseado no seu diretório!
spec:
  secretStoreRefs:
    - name: vault-backend-{{ .Values.clusterName }}
      kind: SecretStore
  selector:
    secret:
      name: {{ .Values.clusterName }}-import # O ACM sempre cria o secret com o nome do cluster
  data:
    - match:
        remoteRef:
          # O caminho no Vault também fica dinâmico para cada cluster
          remoteKey: acm-imports/{{ .Values.clusterName }}/import-yaml
        secretKey: import.yaml
