{{- if .Values.provision.enabled }}
# Secret lido pelo Hive para instalar o cluster. Conteudo montado em _installconfig.tpl.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  install-config.yaml: |
{{ include "azure-ipi-cluster.installConfig" . | indent 4 }}
{{- end }}
