apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-bootstrap
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Garante a limpeza correta ao deletar
spec:
  project: default
  source:
    repoURL: 'https://github.com/seu-usuario/gitops-infra.git'
    targetRevision: HEAD
    path: bootstrap/ # Pasta que contém o seu ApplicationSet
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
