apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-clusters-managed
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/pecorawal/gitops-infra.git'
    targetRevision: main
    path: clusters/ # Onde estão as definições dos clusters
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc' # Deploy no Hub Cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
