apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: import-rosa-01
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/pecorawal/gitops-infra.git'
    targetRevision: main
    path: templates/import-cluster
    helm:
      values: |
        clusterName: "rosa-prod-01"
        cloudType: "ROSA"
        labels:
          cloud: AWS
          vendor: OpenShift
          env: production
          # Label essencial para o ArgoCD gerenciar apps NESTE cluster depois
          apps.open-cluster-management.io/replicate-to-argocd: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-cluster-management # Namespace padrão do Hub
  syncPolicy:
    automated:
      prune: true
