apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: get-hub-kubeconfig
  namespace: open-cluster-management-agent
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aro-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: bootstrap-hub-kubeconfig 
    template:
      type: Opaque
      # O ESO vai decodificar a string do Vault e injetar como texto plano no Secret
      # (O próprio Kubernetes se encarrega de re-encodar em base64 internamente na API)
      data:
        kubeconfig: "{{ .kubeconfig_raw | b64dec }}"
  data:
    # 1. O ESO busca o valor do Vault
    - secretKey: kubeconfig_raw
      remoteRef:
        key: bootstrap-kubeconfig
        property: kubeconfig_base64 # Ajuste se o seu Vault usar properties/keys internas
