apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: install-acm-agent
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/pecorawal/gitops-infra.git
    targetRevision: main
    path: charts/acm-agent-managed
    helm:
      parameters:
        - name: clusterName
          value: "openenv-b26q8"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
